apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
- apiVersion: apps/v1
  kind: Deployment
  spec:
    replicas: '2'
- kind: Service
functionConfig:
  apiVersion: krm.kcl.dev/v1alpha1
  kind: KCLRun
  metadata:
    name: conditionally-add-annotations
  spec:
    params:
      replicas: "5"
      source: |
        params = option("params")
        items = option("items")
        replicas = params.replicas
        setReplicas = lambda items, replicas {
           [item | {if item.kind == "Deployment": spec.replicas = replicas} for item in items]
        }
        items = setReplicas(items, replicas)
